# Custom InSpec resource — psql connection to Aurora-PostgreSQL via
# IAM DB auth, used by the §4 / §5 / §6 / §8.3 controls that need to
# query pg_catalog / information_schema. Phase C of #29.
#
# Connection prerequisites (provisioned by the consumer's infra-bootstrap pipeline):
#   - IAM role `${prefix}-db-scanner` with rds-db:connect action against
#     `dbuser/inspec_scanner`. OIDC-trusted to the calling repository,
#     i.e. `repo:<your-org>/<caller-repo>`.
#   - DB user `inspec_scanner` with `rds_iam` role + read-only grants
#     on pg_catalog + information_schema. No grants on pg_authid (per
#     the #184 discussion — password hashes off-limits).
#   - Network path from the runner to the cluster reader endpoint.
#     Today via the on-demand VPC self-hosted runner shipped in
#     the consumer's infra-bootstrap pipeline; consumers without a private cluster can use a
#     standard runner against a public endpoint.
#
# Auth token is generated by the AWS SDK (`generate_db_auth_token`)
# using the credentials currently in scope (the GitHub Actions OIDC
# session that assumed example_db_scanner). Tokens last 15
# minutes — generated fresh per resource instantiation.
#
# Usage from a control body:
#
#   describe aws_rds_aurora_psql_query.query(
#     "SELECT rolname FROM pg_roles WHERE rolsuper = true"
#   ) do
#     it { should_not be_empty }
#   end
#
# Or with explicit options when running outside the the consumer CI flow:
#
#   q = aws_rds_aurora_psql_query(
#     cluster_endpoint: 'my-cluster.cluster-ro-us-east-1.rds.amazonaws.com',
#     database:         'postgres',
#     db_user:          'inspec_scanner',
#   )
#   describe q.query("SELECT name, setting FROM pg_settings WHERE name = 'ssl'") do
#     its('first.setting') { should eq 'on' }
#   end
#
# Defaults read from inputs when opts aren't provided:
#   cluster_endpoint  <- input('aurora_cluster_endpoint')
#   database          <- input('aurora_database_name')   (default 'postgres')
#   db_user           <- input('aurora_scanner_dbuser')  (default 'inspec_scanner')
#
# `pg` is loaded lazily inside `_connect` so the library is loadable in any
# cinc-auditor runtime — even one without the pg gem installed. Phase-C
# controls degrade through `connection_error` rather than crashing the
# whole profile at library-walk time.

class AwsRdsAuroraPsqlQuery < AwsResourceBase
  name 'aws_rds_aurora_psql_query'
  desc 'Run read-only psql queries against an Aurora-PostgreSQL cluster via IAM DB auth.'

  example "
    describe aws_rds_aurora_psql_query.query(
      \"SELECT rolname FROM pg_roles WHERE rolsuper = true\"
    ) do
      it { should_not be_empty }
    end
  "

  attr_reader :cluster_endpoint, :database, :db_user, :port

  def initialize(opts = {})
    super(opts)
    # AwsResourceBase#validate_parameters with no allow-list rejects every
    # non-standard key with "Unexpected arguments found". The opts documented
    # above were therefore never actually accepted — passing any of them raised
    # at exec time, which is why callers fell back to the (broken) resource-scope
    # input lookup. Declaring them makes the documented contract real. (#7)
    validate_parameters(
      allow: %i[cluster_endpoint endpoint database db_user port region]
    )

    # Inputs are the canonical defaults; opts override.
    # Engine-agnostic input names take precedence; aurora_*-named inputs
    # are kept as deprecated aliases for backward compatibility with
    # consumers that wired them in pre-engine-agnostic-refactor.
    raw_endpoint      = (opts[:cluster_endpoint] || opts[:endpoint] ||
                         _input_or_default_chained(['postgresql_endpoint', 'aurora_cluster_endpoint'], '')).to_s
    # Normalize: strip any `:port` suffix from the endpoint input. The
    # input may arrive as `host` (no port) or `host:5432` (port included).
    # @cluster_endpoint is the host-only form used by PG.connect's
    # `host:` arg; @port carries the port separately. The SDK
    # AuthTokenGenerator wants `host:port` together, which we rebuild
    # from these two when constructing the token-signing endpoint.
    @cluster_endpoint = raw_endpoint.split(':').first.to_s
    @database         = (opts[:database]         ||
                         _input_or_default_chained(['postgresql_database_name', 'aurora_database_name'], 'postgres')).to_s
    @db_user          = (opts[:db_user]          ||
                         _input_or_default_chained(['postgresql_scanner_dbuser', 'aurora_scanner_dbuser'], 'inspec_scanner')).to_s
    @port             = Integer(opts[:port]      ||
                                _input_or_default_chained(['postgresql_port', 'aurora_port'], 5432))
    @region           = (opts[:region]           || ENV['AWS_REGION'] || ENV['AWS_DEFAULT_REGION'] || 'us-east-1').to_s
    @connection       = nil
  end

  def exists?
    !@cluster_endpoint.empty?
  end

  # Lazy-attempts a connection on first call; returns nil on success or a
  # human-readable error string on any failure (no endpoint configured,
  # pg gem missing, IAM token gen failed, psql connect failed, etc.).
  # Use this from controls as a precheck describe before trusting query
  # results — empty results from a failed connection would otherwise
  # silently pass `should be_empty` matchers.
  #
  # An empty endpoint now returns an explicit message rather than nil
  # (so the precheck FAILs with a clear "set postgresql_endpoint" rationale
  # instead of letting the control vacuous-PASS off empty query results).
  def connection_error
    unless exists?
      return "no endpoint reached this resource. Either postgresql_endpoint / " \
             "aurora_cluster_endpoint is genuinely unset, OR the caller built this " \
             "resource without passing one — inputs are NOT readable from resource " \
             "scope (#7). Controls should call `postgresql_query`, which resolves " \
             "inputs at rule scope, rather than instantiating this resource directly."
    end
    _connect
    @resource_failure
  end

  def connected?
    connection_error.nil?
  end

  # Run a SELECT and return the result as an array of hashes
  # ({column-name => value, …}). Returns [] on connection / auth /
  # query error so describe blocks fail cleanly with `should_not be_empty`
  # instead of bubbling Ruby exceptions.
  def query(sql)
    return [] unless exists?
    rows = []
    catch_aws_errors do
      conn = _connect
      return [] if conn.nil?
      result = conn.exec(sql)
      rows = result.to_a
      result.clear if result.respond_to?(:clear)
    end
    rows
  rescue PG::Error => e
    @failed_resource = true
    @resource_failure = e.message
    []
  end

  def to_s
    "Aurora-PostgreSQL @ #{@cluster_endpoint || '<no endpoint>'} (db=#{@database}, user=#{@db_user})"
  end

  private

  # LAST-RESORT fallback only. Inputs are not readable from resource scope --
  # `input()` raises NoMethodError inside a resource class (#7) -- so callers
  # must resolve inputs at RULE scope and pass them as opts. `postgresql_query`
  # in _postgresql_scope_helpers.rb does exactly that and is the supported
  # entry point.
  #
  # The previous `defined?(input)` guard was not sufficient: it resolves truthy,
  # the call then raises, and the rescue path made a configured endpoint look
  # unset. `respond_to?` is the honest test, so the ENV/default path is actually
  # reached when inputs are unavailable.
  def _input_or_default(name, default)
    if respond_to?(:input)
      begin
        val = input(name)
        return val unless val.to_s.empty?
      rescue NoMethodError, NameError
        # inputs genuinely unreachable from here -- fall through
      end
    end
    ENV[name.upcase] || default
  end

  # Try a chain of input names, returning the first non-empty value.
  # Used to prefer engine-agnostic input names (postgresql_*) over the
  # legacy aurora_*-named aliases.
  def _input_or_default_chained(names, default)
    Array(names).each do |name|
      val = _input_or_default(name, '')
      return val unless val.to_s.empty?
    end
    default
  end

  def _connect
    return @connection if @connection && !@connection.finished?
    return nil if @cluster_endpoint.empty?

    begin
      require 'pg' unless defined?(PG)
    rescue LoadError => e
      @failed_resource = true
      @resource_failure = "pg gem not installed in cinc-auditor runtime: #{e.message}. Add via custom Docker image or `gem install pg --no-document` step before exec."
      return nil
    end

    auth_token = _generate_auth_token
    return nil if auth_token.nil?

    # connect_timeout 60s: comfortably covers cold-start TCP accept + SSL
    # handshake + IAM token validation, which can together take 5–15s
    # under load on a freshly-booted runner. 10s (the previous value)
    # was tight enough to clip transient slowness as the user observed
    # in the 2026-05-13 exec. The resource instantiates per-control
    # (8 db-connection controls), so each control pays the connect
    # cost — generous timeout is cheaper than spurious skip-on-precheck
    # failures. Job-level timeout (15 min in validate.yml) still bounds
    # total exec time.
    @connection = PG.connect(
      host:     @cluster_endpoint,
      port:     @port,
      user:     @db_user,
      password: auth_token,
      dbname:   @database,
      sslmode:  'require',
      connect_timeout: 60,
    )
    @connection
  rescue PG::Error => e
    @failed_resource = true
    @resource_failure = "psql connect failed: #{e.message}"
    nil
  end

  # IAM DB auth token generation lives on the standalone
  # `Aws::RDS::AuthTokenGenerator` utility class, NOT on
  # `Aws::RDS::Client`. The generator signs a presigned URL using the
  # credentials currently in scope (in CI: the OIDC-assumed
  # example_db_scanner role; locally: whatever the InSpec
  # session resolved).
  #
  # Version-agnostic method dispatch: the generator's method name has
  # varied across aws-sdk-rds gem versions. Modern (1.311.x) defines
  # `generate_auth_token` with `auth_token` aliased to it. Older
  # versions may have only one or the other. The runner image differs
  # from the cinc-auditor docker image's gem set (runner uses a
  # natively-installed cinc), so we probe respond_to? rather than
  # assume the modern name.
  #
  # Credentials are pulled from the already-configured train-aws RDS
  # client — same identity that's already authorised for
  # rds-db:connect against the inspec_scanner DB user. Passing
  # `credentials:` to the constructor is mandatory (the constructor
  # uses `options.fetch(:credentials)` which raises KeyError otherwise).
  def _generate_auth_token
    creds = @aws.rds_client.config.credentials
    generator = Aws::RDS::AuthTokenGenerator.new(credentials: creds)

    # @cluster_endpoint is already host-only (normalized in initialize).
    # SDK AuthTokenGenerator wants `host:port` together — build it
    # explicitly here.
    args = {
      region:    @region,
      endpoint:  "#{@cluster_endpoint}:#{@port}",
      user_name: @db_user,
    }

    if generator.respond_to?(:generate_auth_token)
      generator.generate_auth_token(args)
    elsif generator.respond_to?(:auth_token)
      generator.auth_token(args)
    else
      available = (generator.methods - Object.methods).sort.join(', ')
      raise NoMethodError, "Aws::RDS::AuthTokenGenerator has neither generate_auth_token nor auth_token methods. " \
                            "aws-sdk-rds gem on the runner may be older / patched. Available instance methods: #{available}"
    end
  rescue Aws::Errors::ServiceError, Aws::Errors::MissingCredentialsError, StandardError => e
    @failed_resource = true
    @resource_failure = "AuthTokenGenerator#generate_auth_token failed: #{e.class.name}: #{e.message}"
    nil
  end
end
