# encoding: UTF-8

control 'C-3.1.2' do
  title 'Ensure the log destinations are set correctly'
  desc  "
    PostgreSQL supports several methods for logging server messages, including `stderr`, `csvlog`, `syslog`, and `jsonlog`. On Windows, `eventlog` is also supported. One or more of these destinations should be set for server log output.

    If `log_destination` is not set, then any log messages generated by the core PostgreSQL processes will be lost.
  "
  desc  'rationale', "
    PostgreSQL supports several methods for logging server messages, including `stderr`, `csvlog`, `syslog`, and `jsonlog`. On Windows, `eventlog` is also supported. One or more of these destinations should be set for server log output.

    If `log_destination` is not set, then any log messages generated by the core PostgreSQL processes will be lost.
  "
  desc  'check', "
    Execute the following SQL statement to view the currently active log destinations:
    ```
    postgres=# show log_destination;
     log_destination
    -----------------
     stderr
    (1 row)
    ```
    The log destinations should comply with your organization's policies on logging. If all the expected log destinations are not set, this is a fail.
  "
  desc  'fix', "
    Execute the following SQL statements to remediate this setting (in this example, setting the log destination to `csvlog`):
    ```
    postgres=# alter system set log_destination = 'csvlog';
    ALTER SYSTEM
    postgres=# select pg_reload_conf();
     pg_reload_conf
    ----------------
     t
    (1 row)
    ```
    Note: If more than one log destination is to be used, set this parameter to a list of desired log destinations separated by commas (e.g. '`csvlog, stderr`').
  "
  tag severity:              'medium'
  tag severity_source:       'unassessed'
  tag nist:                  ['AC-2 f', 'IA-2 (2)', 'AU-2 a', 'AU-3 a']
  tag cci:                   ['CCI-000011', 'CCI-000766', 'CCI-000123', 'CCI-000130']
  tag cis_number:            '3.1.2'
  tag cis_rid:               '3.1.2'
  tag cis_benchmark:         'CIS PostgreSQL Benchmark (v14–v18)'
  tag postgresql_versions:    ['14', '15', '16', '17', '18']
  tag applicable_partitions: ['aws', 'aws-us-gov']
  tag implementation_status: 'implemented'
  tag cis_rule_id:           'SV-030102r1_rule'
  tag cis_version:           '1.0.0'
  tag cis_level:             1
  tag cis_scored:            true

  applicable_partition = ['aws', 'aws-us-gov'].include?(input('aws_partition'))
  applicable_version   = ['14', '15', '16', '17', '18'].include?(input('postgresql_version').to_s)
  applicable           = applicable_partition && applicable_version

  impact 0.5
  impact 0.0 unless applicable

  only_if("Control out of scope (partition=#{input('aws_partition')}, postgresql_version=#{input('postgresql_version')})") do
    applicable
  end

  postgresql_parameter_groups.each do |target|
    next if target[:pg_name].nil?
    if target[:resource].respond_to?(:connection_error) && target[:resource].connection_error
      describe "RDS DB Parameter Group: #{target[:pg_name]}" do
        skip "pending-resource: parameter-group lookup failed for #{target[:id]} — #{target[:resource].connection_error}"
      end
      next
    end
    describe target[:resource] do
      its("parameter_value('log_destination')") { should match_pg_param(/csvlog|stderr/) }
    end
  end
end
